# Generated by Django 5.2.7 on 2025-10-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artifacts", "0001_initial"),
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScienceField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Название области науки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Область науки",
                "verbose_name_plural": "Области науки",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalFigure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_name", models.CharField(max_length=255, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=255, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(max_length=255, verbose_name="Отчество"),
                ),
                ("birth_date", models.DateField(verbose_name="Дата рождения")),
                (
                    "death_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата смерти"),
                ),
                ("description", models.TextField(verbose_name="Краткое описание")),
                ("biography", models.TextField(verbose_name="Биография")),
                (
                    "artifacts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="historical_figures",
                        to="artifacts.artifact",
                        verbose_name="Артефакты",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="historical_figures",
                        to="shared.image",
                        verbose_name="Изображения",
                    ),
                ),
                (
                    "science_fields",
                    models.ManyToManyField(
                        related_name="historical_figures",
                        to="historical_figures.sciencefield",
                        verbose_name="Области науки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Историческая личность",
                "verbose_name_plural": "Исторические личности",
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
