# Generated by Django 5.2.7 on 2025-10-04 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtifactCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название категории"),
                ),
            ],
            options={
                "verbose_name": "Категория артефакта",
                "verbose_name_plural": "Категории артефактов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HallCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название категории"),
                ),
            ],
            options={
                "verbose_name": "Категория зала",
                "verbose_name_plural": "Категории залов",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название зала"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shared.image",
                        verbose_name="Изображение зала",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="artifacts.hallcategory",
                        verbose_name="Категория зала",
                    ),
                ),
            ],
            options={
                "verbose_name": "Зал",
                "verbose_name_plural": "Залы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название артефакта"),
                ),
                ("description", models.TextField(verbose_name="Описание артефакта")),
                ("creation_year", models.IntegerField(verbose_name="Год создания")),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True,
                        related_name="artifacts",
                        to="shared.image",
                        verbose_name="Изображения",
                    ),
                ),
                (
                    "model_3d",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shared.model3d",
                        verbose_name="3D модель",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="artifacts.artifactcategory",
                        verbose_name="Категория артефакта",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="artifacts.hall",
                        verbose_name="Зал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Артефакт",
                "verbose_name_plural": "Артефакты",
                "ordering": ["name"],
            },
        ),
    ]
