# Generated by Django 5.2.7 on 2025-10-05 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="url",
        ),
        migrations.RemoveField(
            model_name="model3d",
            name="url",
        ),
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "webp", "svg"]
                    )
                ],
                verbose_name="Изображение",
            ),
        ),
        migrations.AddField(
            model_name="model3d",
            name="model",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="models3d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["glb", "gltf"]
                    )
                ],
                verbose_name="3D модель",
            ),
        ),
    ]
